language: python
sudo: false

python:
  - 2.7
  - pypy
  - 3.4
  - 3.5


# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install  python-coveralls


# Command to run tests, e.g. python setup.py test
script:
  - coverage run --source=tests,rest_framework_cache setup.py test


# Report to coveralls
after_success:
  - coveralls

env:
  - DJANGO_VERSION=1.8.11
  - DJANGO_VERSION=1.9.4

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_VERSION='>=1.8,<1.9'
    - python: "3.2"
      env: DJANGO_VERSION='>=1.9,<1.10'
    - python: "3.3"
      env: DJANGO_VERSION='>=1.9,<1.10'